export default [
    "Chrząszcz brzmi w trzcinie w Szczebrzeszynie",
    "stół z powyłamywanymi nogami",
    "Ala ma kota",
    "wyrewolwerowany kaloryfer",
    "Szedł Sasza suchą szosą",
    "Król Karol kupił królowej Karolinie korale koloru koralowego",
    "Jola lojalna, Lola nielojalna",
    "Ząb, zupa zębowa, dąb, zupa dębowa",
    "To cóż, że ze Szwecji",
    "Konstantynopolitańczykowianeczkówna",
    "Leży Jerzy na wieży i nie wierzy, że w tej wieży leży gniazdo nietoperzy",
    "Krtań krztusiła krztyną rtęci",
    "Wlazł kotek na płotek i mruga, ładna to piosenka niedługa",
    "Niedługa, niekrótka, lecz w sam raz, zaśpiewaj koteczku, jeszcze raz",
];